CREATE TABLE groups
(
    id_group bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(255),
    PRIMARY KEY (id_group)
);

CREATE TABLE group_roles
(
    group_id bigint NOT NULL,
    role_id bigint NOT NULL
);

CREATE TABLE roles
(
    id_role bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(255),
    PRIMARY KEY (id_role)
);

CREATE TABLE users
(
    id_user bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    active boolean,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    PRIMARY KEY (id_user)
);

CREATE TABLE user_groups
(
    user_id bigint NOT NULL,
    group_id bigint NOT NULL,
    PRIMARY KEY (group_id, user_id)
);

ALTER TABLE group_roles
    ADD FOREIGN KEY (role_id)
    REFERENCES roles (id_role);

ALTER TABLE group_roles
    ADD FOREIGN KEY (group_id)
    REFERENCES groups (id_group);

ALTER TABLE user_groups
    ADD FOREIGN KEY (group_id)
    REFERENCES groups (id_group);

ALTER TABLE user_groups
    ADD FOREIGN KEY (user_id)
    REFERENCES users (id_user);