CREATE TABLE products
(
    id_product bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(255),
	quantity decimal(10,3),
	price decimal(10,2),
    PRIMARY KEY (id_product)
);

CREATE TABLE orders
(
    id_order bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    date_order timestamp NOT NULL,
	amount_order decimal(10,2),
	PRIMARY KEY (id_order)
);

CREATE TABLE item_orders
(
    id_item_order bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	date_item timestamp,
    quantity decimal(10,3),
	price decimal(10,2),
	subtotal decimal(10,2),
	order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    PRIMARY KEY (id_item_order)
);

CREATE TABLE order_codes
(
    id_order_code bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	code character varying(255),
    PRIMARY KEY (id_order_code)
);

ALTER TABLE item_orders
    ADD FOREIGN KEY (order_id)
    REFERENCES orders (id_order);

ALTER TABLE item_orders
	ADD FOREIGN KEY (product_id)
    REFERENCES products (id_product);
